### ISSUE TITLE
Image seems to be missing

### ISSUE THREAD

**Issue by hugo-sid** [antedoro/arberia#1]
## Missing image issue
The Netlify link in the about section of your repo shows up like this.
![image](https://user-images.githubusercontent.com/122173059/224108943-a7a18df7-8c89-432d-93b3-8bcf14101a5a.png).
One of the image seems to be missing.

## Additional info for debugging
When I right click and do open image in a new tab, it opens up `https://arberiatheme.netlify.app/post-with-sidebar/post-with-sidebar.webp480w`.

**Comment by antedoro** [comment]
I see It regularly. 
When I click on featured image opens correcly

<img width="1252" alt="Screenshot 2023-03-09 alle 18 49 47" src="https://user-images.githubusercontent.com/3458176/224112920-3737596a-3da4-45cd-9e18-247893d11578.png">

**Comment by hugo-sid** [comment]
That's strange.

**Comment by antedoro** [comment]
I tested with firefox, chrome and Safari.
Please make the same.

**Comment by hugo-sid** [comment]
I tested with Firefox and there was no issue.

But the issue was present on Brave and MS edge.

**Comment by antedoro** [comment]
The next week I will see to find the bug.
