### ISSUE TITLE
Error on Cloudflare Pages Install

### ISSUE THREAD

**Issue by AnwarSafii** [antedoro/arberia#2]
I try to install on cloudflare pages, but i have error this:
`10:16:46.144 | Installing Hugo 0.111.2
-- | --
10:16:48.659 | hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended linux/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=gohugoio
10:16:48.664 | Started restoring cached go cache
10:16:48.694 | Finished restoring cached go cache
10:16:48.887 | go version go1.14.4 linux/amd64
10:16:48.903 | go version go1.14.4 linux/amd64
10:16:48.907 | Installing missing commands
10:16:48.907 | Verify run directory
10:16:48.907 | Executing user command: hugo
10:16:48.960 | Error: module "arberia" not found; either add it as a Hugo Module or store it in "/opt/buildhome/repo/themes".: module does not exist
10:16:48.960 | Total in 3 ms
10:16:48.969 | Failed: build command exited with code: 255
10:16:49.779 | Failed: an internal error occurred`

**Comment by antedoro** [comment]
It seems that you haven't declared arberia as a Theme in the config.

Copy content of /exampleSite/ folder on root directory and configure che config.tolm
